server:
  port: 9102
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  cloud:
    config:
      import-check:
        enabled: false
      uri: http://localhost:9101/